server:
  port: 9999
spring:
  datasource:
    username: root
    password: "!QAZxcvfr432"
    url: jdbc:mysql://172.10.3.165:3306/mi?useUnicode=true&amp;characterEncoding=utf-8&amp;allowMultiQueries=true
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.shankephone.mi.mqtt.model  # 注意：对应实体类的路径